[build]
  # Step into the frontend folder
  base = "frontend"
  
  # Leave this empty because you don't have a package.json/build step
  command = ""
  
  # Tell Netlify to publish the current folder (frontend)
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200